services:
  discord-bot:
    build:
      context: .
    container_name: discord-bot
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      TZ: America/Panama
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
